data_plugin: KTCDataPlugin
mesh_path: data/Mesh/
levels: [1, 2, 3, 4, 5, 6, 7]
samples: [A, B, C]
methods: [BackProjection, GaussNewton]
dataset_root: "C:/Users/49176/Desktop/main project/10986692/EvaluationData_full/EvaluationData_full"
output_dir: outputs/
